language: node_js
node_js:
  - "stable"

dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

before_install:
  - npm install

#install:
#  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: registry
  on:
branch: master
