language: node_js
node_js:
  - "stable"

dist: trusty
sudo: false

branches:
  only:
  - develop

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build

deploy:
  provider: develop
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: develop

