"Time Zone": "Europe/London"
encoding: utf-8
lsi: true
title: Bio Docker
url: http://biodocker.org/
defaults:
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "pages"
